name: Verificaciones

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Carga rama de Git
        uses: actions/checkout@v4

      - name: Instala Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Carga caché Nix
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Carga caché general
        uses: actions/cache@v4
        with:
          path: |
            repl/elm-stuff
            .direnv
            .pnpm-store
            ~/.local/share/pnpm/store/v3
            ~/.elm
          key: ${{ runner.os }}-cache

      - name: Verifica
        run: nix develop .#ci --command just check

      - run: |
          nix develop .#ci --command pnpm store path
          nix develop .#ci --command echo $HOME

