name: Verificaciones

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            repl/elm-stuff
            .direnv
            .pnpm-store
            ~/.elm
            /nix
          key: ${{ runner.os }}-cache
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop .#ci --command just check
