name: Verificaciones

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DEV_SHELL_NAME: ci

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop .#ci --command bash -c 'just check'
