name: Verificaciones

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Carga rama de Git
        uses: actions/checkout@v4
      - name: Carga caché
        uses: actions/cache@v4
        with:
          path: |
            repl/elm-stuff
            .direnv
            .pnpm-store
            ~/.elm
            /nix
          key: ${{ runner.os }}-cache
      - name: Instala Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Verifica
        run: nix develop .#ci --command just check
