name: Verificaciones

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Carga rama de Git
        uses: actions/checkout@v4

      - name: Instala Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Carga caché Nix
        uses: DeterminateSystems/magic-nix-cache-action@5626df0a8b8f16cb060538f6d3041500a2d10cb0

      - name: Carga caché general
        uses: actions/cache@v4
        with:
          path: |
            .direnv
            .pnpm-store
            ~/.local/share/pnpm
            ~/.elm
          key: ${{ runner.os }}-cache

      - name: Información del entorno
        run: |
          nix develop .#ci --command pnpm store path
          echo "HOME=$HOME"
          echo "ELM_HOME=$ELM_HOME"

      - name: Verifica
        run: nix develop .#ci --command just check
