name: Publicación

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Carga rama de Git
        uses: actions/checkout@v4
      - name: Carga caché
        uses: actions/cache@v4
        with:
          path: |
            repl/elm-stuff
            .direnv
            .pnpm-store
            ~/.elm
            /nix
          key: ${{ runner.os }}-cache
      - name: Instala Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Sube a GH Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          nix develop .#ci --command just deploy-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
