name: Publicación

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Carga rama de Git
        uses: actions/checkout@v4

      - name: Instala Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Carga caché Nix
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Carga caché general
        uses: actions/cache@v4
        with:
          path: |
            repl/elm-stuff
            .direnv
            .pnpm-store
            ~/.elm
          key: ${{ runner.os }}-cache

      - name: Sube a GH Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          nix develop .#ci --command just deploy-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
